from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from uuid import UUID
import uuid
import logging

from app.models.pg_models import (
    Product,
    ProcurementType,
    ManufacturingOrder,
    ManufacturingOrderStatus,
    ManufacturingOrderSource,
    BoMOperation,
    BoMLine,
    WorkOrder,
    WorkOrderStatus,
    PurchaseOrder,
    PurchaseOrderStatus,
    PurchaseOrderSource,
    PurchaseOrderLine,
    PaymentStatus,
    PaymentMethod
)

logger = logging.getLogger(__name__)

async def trigger_procurement(
    product_id: UUID,
    shortage_qty: float,
    db: AsyncSession,
    depth: int = 0
) -> None:
    if shortage_qty <= 0:
        return

    if depth > 10:
        logger.warning(f"Procurement recursion limit reached (depth={depth}) for product {product_id}. Aborting to prevent infinite loop.")
        return

    # 1. Fetch Product
    prod_res = await db.execute(select(Product).where(Product.id == product_id))
    product = prod_res.scalars().first()
    if not product:
        logger.warning(f"Product {product_id} not found in procurement trigger.")
        return

    if not product.procure_on_demand:
        logger.info(f"Product {product.name} ({product_id}) does not have procure_on_demand enabled. Skipping auto-procurement.")
        return

    # 2. Case: Manufacturing
    if product.procurement_type == ProcurementType.Manufacturing:
        if not product.bom_id:
            logger.error(f"Manufacturing procurement strategy selected for product {product.name} ({product_id}) but no bom_id is configured.")
            return

        order_number = f"MO-AUTO-{uuid.uuid4().hex[:6].upper()}"
        db_mo = ManufacturingOrder(
            product_id=product.id,
            bom_id=product.bom_id,
            quantity_to_produce=shortage_qty,
            status=ManufacturingOrderStatus.Draft,
            source=ManufacturingOrderSource.AutoGenerated,
            order_number=order_number
        )
        db.add(db_mo)
        await db.flush()

        # Generate default work orders
        ops_res = await db.execute(
            select(BoMOperation)
            .where(BoMOperation.bom_id == product.bom_id)
            .order_by(BoMOperation.sequence)
        )
        operations = ops_res.scalars().all()
        for op in operations:
            wo = WorkOrder(
                manufacturing_order_id=db_mo.id,
                operation_name=op.operation_name,
                sequence=op.sequence,
                work_center_id=op.work_center_id,
                status=WorkOrderStatus.Pending
            )
            db.add(wo)

        # Trigger recursive procurement checks for components of the new MO
        await check_mo_components_for_procurement(db_mo.id, db, depth + 1)

    # 3. Case: Purchase
    elif product.procurement_type == ProcurementType.Purchase:
        if not product.vendor_id:
            logger.error(f"Purchase procurement strategy selected for product {product.name} ({product_id}) but no vendor_id is configured.")
            return

        # Check if there is already an open Draft AutoGenerated PO for this vendor to bundle lines
        po_res = await db.execute(
            select(PurchaseOrder)
            .where(
                PurchaseOrder.vendor_id == product.vendor_id,
                PurchaseOrder.status == PurchaseOrderStatus.Draft,
                PurchaseOrder.source == PurchaseOrderSource.AutoGenerated
            )
        )
        db_po = po_res.scalars().first()

        if not db_po:
            order_number = f"PO-AUTO-{uuid.uuid4().hex[:6].upper()}"
            db_po = PurchaseOrder(
                vendor_id=product.vendor_id,
                status=PurchaseOrderStatus.Draft,
                source=PurchaseOrderSource.AutoGenerated,
                order_number=order_number,
                payment_status=PaymentStatus.Unpaid,
                payment_method=PaymentMethod.Wallet
            )
            db.add(db_po)
            await db.flush()

        # Add or update line on the PO
        line_res = await db.execute(
            select(PurchaseOrderLine)
            .where(
                PurchaseOrderLine.purchase_order_id == db_po.id,
                PurchaseOrderLine.product_id == product.id
            )
        )
        db_line = line_res.scalars().first()

        if db_line:
            db_line.quantity_ordered += shortage_qty
        else:
            db_line = PurchaseOrderLine(
                purchase_order_id=db_po.id,
                product_id=product.id,
                quantity_ordered=shortage_qty,
                unit_cost=product.cost_price
            )
            db.add(db_line)

async def check_mo_components_for_procurement(
    mo_id: UUID,
    db: AsyncSession,
    depth: int = 0
) -> None:
    # 1. Fetch MO details
    mo_res = await db.execute(select(ManufacturingOrder).where(ManufacturingOrder.id == mo_id))
    mo = mo_res.scalars().first()
    if not mo:
        return

    # 2. Explode BoM Lines
    bom_lines_res = await db.execute(select(BoMLine).where(BoMLine.bom_id == mo.bom_id))
    lines = bom_lines_res.scalars().all()

    # 3. For each component, check shortages
    for line in lines:
        required_qty = line.quantity_required * mo.quantity_to_produce
        
        prod_res = await db.execute(select(Product).where(Product.id == line.component_product_id))
        product = prod_res.scalars().first()
        if product:
            free_qty = product.on_hand_qty - product.reserved_qty
            shortage = required_qty - free_qty
            
            if shortage > 0:
                await trigger_procurement(product.id, shortage, db, depth)
