"""add_invoices_table

Revision ID: 4f63d505529b
Revises: 5fcca179a42e
Create Date: 2026-06-21 06:50:09.804937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f63d505529b'
down_revision: Union[str, None] = '5fcca179a42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SalesInvoice', 'PurchaseInvoice', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Issued', 'Paid', 'Cancelled', name='invoicestatus'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=False),
    sa.Column('party_email', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('gcs_url', sa.String(), nullable=True),
    sa.Column('gcs_blob', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
