"""add_products_supplied_and_rating_to_vendors

Revision ID: 5fcca179a42e
Revises: 60b09cf7ea3d
Create Date: 2026-06-21 05:27:43.084730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcca179a42e'
down_revision: Union[str, None] = '60b09cf7ea3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('products_supplied', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'rating')
    op.drop_column('vendors', 'products_supplied')
    # ### end Alembic commands ###
